### PR TITLE
Use Yajl as default Serializer

### PR DESCRIPTION
**Pull request by silwalprabin**
* Add Json, Yajl serializer
* Make Yajl as default serializer
* Fixed https://github.com/EnjoyTech/parallel_workforce/issues/1

### CODE REVIEW

**Comment by ioquatix** [comment]
Understood, do you want to merge this and then change the behaviour to suit your requirements?

**Comment by ioquatix** [comment]
Also, just a quick check, but wasn't the problem relating to serializing binary data (generated by Marshal) into a sidekiq JSON message? Correct me if I'm wrong.

**Comment by michaelgpearce** [comment]
> Also, just a quick check, but wasn't the problem relating to serializing binary data (generated by Marshal) into a sidekiq JSON message? Correct me if I'm wrong.

I assume there were some characters that Sidekiq doesn't like that a JSON serializer escapes.

I'll make a change that includes your change combined with `Marshal` (see https://github.com/EnjoyTech/parallel_workforce/issues/1#issuecomment-659976700). It's a bit of a performance hit, but it should aid in compatibility. If people need more performance, they can write their own serializer as needed.

**Comment by michaelgpearce** [comment]
Fixed in version 2 by combining `JSON` serialization with Marshal loading in default serializer `JsonMarshal` class.

**Pull request closed without merging**
